In [1]:
%pip install mlxtend --upgrade

Requirement already satisfied: mlxtend in /usr/local/lib/python3.7/dist-packages (0.14.0)
Collecting mlxtend
  Downloading mlxtend-0.19.0-py2.py3-none-any.whl (1.3 MB)
     |████████████████████████████████| 1.3 MB 14.2 MB/s
Requirement already satisfied: matplotlib>=3.0.0 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (3.2.2)
Requirement already satisfied: joblib>=0.13.2 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.1.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from mlxtend) (57.4.0)
Requirement already satisfied: numpy>=1.16.2 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.21.5)
Requirement already satisfied: scikit-learn>=0.20.3 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.0.2)
Requirement already satisfied: pandas>=0.24.2 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.3.5)
Requirement already satisfied: scipy>=1.2.1 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.4.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.0.0->mlxtend) (3.0.7)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.0.0->mlxtend) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.3.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.2->mlxtend) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.1->matplotlib>=3.0.0->mlxtend) (1.15.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.20.3->mlxtend) (3.1.0)
Installing collected packages: mlxtend
  Attempting uninstall: mlxtend
    Found existing installation: mlxtend 0.14.0
    Uninstalling mlxtend-0.14.0:
      Successfully uninstalled mlxtend-0.14.0
Successfully installed mlxtend-0.19.0

In [2]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder 
from mlxtend.frequent_patterns import association_rules
from mlxtend.frequent_patterns import fpgrowth

In [4]:
dataset = [['TFIOS', '5 feet apart', 'Walk to remember'], ['TFIOS', 'Walk to remember'],
['Divergent', 'Harry Potter','Walk to remember'], ['TFIOS', 'Five feet apart'],
['Divergent','Harry Potter']] 
te = TransactionEncoder()
te_array = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_array, columns=te.columns_)

In [5]:
df

   5 feet apart  Divergent  ...  TFIOS  Walk to remember
0          True      False  ...   True              True
1         False      False  ...   True              True
2         False       True  ...  False              True
3         False      False  ...   True             False
4         False       True  ...  False             False

[5 rows x 6 columns]

In [6]:
frequent_itemsets_fp=fpgrowth(df, min_support=0.02, use_colnames=True)

In [7]:
frequent_itemsets_fp

    support                                     itemsets
0       0.6                           (Walk to remember)
1       0.6                                      (TFIOS)
2       0.2                               (5 feet apart)
3       0.4                               (Harry Potter)
4       0.4                                  (Divergent)
5       0.2                            (Five feet apart)
6       0.4                    (TFIOS, Walk to remember)
7       0.2                        (TFIOS, 5 feet apart)
8       0.2             (Walk to remember, 5 feet apart)
9       0.2      (Walk to remember, TFIOS, 5 feet apart)
10      0.2             (Harry Potter, Walk to remember)
11      0.4                    (Divergent, Harry Potter)
12      0.2                (Divergent, Walk to remember)
13      0.2  (Divergent, Harry Potter, Walk to remember)
14      0.2                     (Five feet apart, TFIOS)

In [9]:
rules_fp = association_rules(frequent_itemsets_fp, metric="confidence", min_threshold=0.8)

In [10]:
rules_fp

                        antecedents  ... conviction
0                    (5 feet apart)  ...        inf
1                    (5 feet apart)  ...        inf
2  (5 feet apart, Walk to remember)  ...        inf
3             (TFIOS, 5 feet apart)  ...        inf
4                    (5 feet apart)  ...        inf
5                       (Divergent)  ...        inf
6                    (Harry Potter)  ...        inf
7     (Divergent, Walk to remember)  ...        inf
8  (Harry Potter, Walk to remember)  ...        inf
9                 (Five feet apart)  ...        inf

[10 rows x 9 columns]